// Generated by tools/build_oui_table.py. Do not edit by hand.
#pragma once

#include <stddef.h>

static constexpr const char* kTargetOuis[] = {
    "b4:1e:52",  // Flock Safety: direct_ieee
};
static constexpr size_t kTargetOuiCount = sizeof(kTargetOuis) / sizeof(kTargetOuis[0]);
