#!/usr/bin/env python3
"""Generate the firmware OUI header from a reviewed CSV table."""

import argparse
import csv
import re
from pathlib import Path


PREFIX = re.compile(r"^[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}$")
REQUIRED_COLUMNS = {"prefix", "label", "evidence", "source", "enabled", "notes"}


def parse_table(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as stream:
        reader = csv.DictReader(stream)
        if reader.fieldnames is None or not REQUIRED_COLUMNS.issubset(reader.fieldnames):
            missing = sorted(REQUIRED_COLUMNS - set(reader.fieldnames or []))
            raise ValueError(f"missing required CSV columns: {', '.join(missing)}")

        rows = []
        seen = set()
        for line_number, row in enumerate(reader, start=2):
            if row["enabled"].strip() not in {"0", "1"}:
                raise ValueError(f"line {line_number}: enabled must be 0 or 1")
            if row["enabled"].strip() == "0":
                continue

            prefix = row["prefix"].strip().lower()
            if not PREFIX.fullmatch(prefix):
                raise ValueError(f"line {line_number}: invalid OUI prefix {prefix!r}")
            if prefix in seen:
                raise ValueError(f"line {line_number}: duplicate OUI prefix {prefix}")
            seen.add(prefix)
            rows.append({key: row[key].strip() for key in REQUIRED_COLUMNS})

    if not rows:
        raise ValueError("the generated firmware table cannot be empty")
    return rows


def generate(rows: list[dict[str, str]], output: Path) -> None:
    lines = [
        "// Generated by tools/build_oui_table.py. Do not edit by hand.",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "",
        "static constexpr const char* kTargetOuis[] = {",
    ]
    for row in rows:
        lines.append(f'    "{row["prefix"]}",  // {row["label"]}: {row["evidence"]}')
    lines.extend([
        "};",
        "static constexpr size_t kTargetOuiCount = sizeof(kTargetOuis) / sizeof(kTargetOuis[0]);",
        "",
    ])
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=root / "datasets" / "flock_oui_table.csv")
    parser.add_argument("--output", type=Path, default=root / "generated_oui_table.h")
    args = parser.parse_args()

    rows = parse_table(args.input)
    generate(rows, args.output)
    print(f"Generated {args.output} with {len(rows)} enabled OUI prefix(es).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
